name: SimpleAutoMessage
main: com.vandendaelen.simpleautomessage.SimpleAutoMessage
version: 0.2
author: LotuxPunk
website: https://github.com/LotuxPunk/SimpleAutoMessage
commands:
  samtime:
    description: Set time between 2 messages
    usage: /samtime {minutes}