name: AutoMessageDisplayer
main: com.vandendaelen.automessagedisplayer.AutoMessageDisplayer
version: 0.8
author: LotuxPunk
website: https://github.com/LotuxPunk/AutoMessageDisplayer
commands:
  amdtime:
    description: Set time between 2 messages
    usage: /amdtime {minutes}
  amdrandom:
    description: Enable random broadcast
    usage: /amdrandom true/false
  amdlist:
    description: Show list of messages
    usage: /amdlist
permissions:
  automessagedisplayer.*:
    description: Gives access to all AMD commands
    children:
      automessagedisplayer.settime:
        description: Allow you to set time between 2 messages (/samtime)
        default: op
      automessagedisplayer.setrandom:
        description: Allow top set random broadcast
        default: op
      automessagedisplayer.list:
        description: Allow top show list of messages
        default: op