name: AutoMessageDisplayer
main: com.vandendaelen.automessagedisplayer.AutoMessageDisplayer
version: 0.11
author: LotuxPunk
website: https://github.com/LotuxPunk/AutoMessageDisplayer
commands:
  amdtime:
    description: Set time between 2 messages
    usage: /amdtime {minutes}
  amdrandom:
    description: Enable random broadcast
    usage: /amdrandom true/false
  amdlist:
    description: Show list of messages
    usage: /amdlist
  amdshow:
    description: Broadcast a message manually
    usage: /amdshow [number]
  amdadd:
    description: Add a message
    usage: /amdadd [message]
permissions:
  automessagedisplayer.*:
    description: Gives access to all AMD commands
    children:
      automessagedisplayer.settime:
        description: Allow you to set time between 2 messages (/samtime)
        default: op
      automessagedisplayer.setrandom:
        description: Allow top set random broadcast
        default: op
      automessagedisplayer.list:
        description: Allow top show list of messages
        default: op
      automessagedisplayer.show:
        description: Allow to broadcast a message manually
        default: op
      automessagedisplayer.add:
        description: Allow to add a message
        default: op